# Generated by Django 5.1.7 on 2025-11-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaWeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.URLField(blank=True, null=True, verbose_name='Imagen (URL)'),
        ),
    ]
